version: '3.8'

services:
  order_manager_bot:
    # Use the local Dockerfile in the current directory
    build: 
      context: ./order_manager_bot
      dockerfile: DockerFile
    container_name: order_manager_bot
    restart: unless-stopped
    ports:
      - "5000:8080"
    environment:
      VERIFY_TOKEN: ${VERIFY_TOKEN}
      WHATSAPP_TOKEN: ${WHATSAPP_TOKEN}
      PHONE_NUMBER_ID: ${PHONE_NUMBER_ID}
      GRAPH_API_URL: ${GRAPH_API_URL}
      SPREADSHEET_ID: ${SPREADSHEET_ID}
      CREDENTIALS_FILE: ${CREDENTIALS_FILE}
      PORT: 8080
      CALENDAR_ID: ${CALENDAR_ID}
      DRIVE_FOLDER_ID: ${DRIVE_FOLDER_ID}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_FOLDER: ${CLOUDINARY_FOLDER}


     
